version: '3.9'
services:
  telegraf-system:
    image: telegraf:latest
    volumes:
      - ./system_performance.conf:/etc/telegraf/telegraf.conf:ro
      - ./container_stats:/tmp/:rw
    networks:
      - telegraf
networks: 
  telegraf:
    name: telegraf
