version: '3.9'
services:
  telegraf-system:
    image: telegraf:test
    user: telegraf
    volumes:
      - ./system_performance.conf:/etc/telegraf/telegraf.conf:ro
      - ./container_stats:/tmp/:rw
      - /:/hostfs:ro
    environment:
      - HOST_ETC=/hostfs/etc 
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    networks:
      - telegraf
    privileged: true
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=telegraf
      - DOCKER_INFLUXDB_INIT_PASSWORD=telegraf
      - DOCKER_INFLUXDB_INIT_ORG=telegraf 
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=telegraf
    networks:
      - telegraf
networks: 
  telegraf:
    name: telegraf
